// Generated by IcedCoffeeScript 1.6.2a
(function() {
  var browser, fn, node;



  browser = require('./browser.coffee');

  exports.PpBuffer = typeof window !== "undefined" && window !== null ? browser.PpBuffer : (fn = "./node", node = require(fn), node.PpBuffer);

  exports.force = function(which) {
    return exports.PpBuffer = which;
  };

}).call(this);
