// Generated by IcedCoffeeScript 1.6.2a
(function() {
  var browser, fn, node, which;



  browser = require('./browser');

  which = which != null ? which : typeof window !== "undefined" && window !== null ? (console.log("A"), browser.PpBuffer) : (console.log("B"), fn = "./node", node = require(fn), node.PpBuffer);

  exports.force = function(w) {
    which = w;
    return exports.PpBuffer = which;
  };

  exports.PpBuffer = which;

}).call(this);
