// Generated by IcedCoffeeScript 1.3.3g
(function() {
  var Buffer, C, Packer, U32MAX, floats, is_array, is_int, pow2, rshift, twos_compl, u64max_minus_i, _ref;

  C = require('./const').C;

  Buffer = require('./buffer').Buffer;

  _ref = require('./util'), pow2 = _ref.pow2, rshift = _ref.rshift, twos_compl = _ref.twos_compl, U32MAX = _ref.U32MAX;

  floats = require('./floats');

  is_array = function(x) {
    return Object.prototype.toString.call(x) === '[object Array]';
  };

  is_int = function(f) {
    return Math.floor(f) === f;
  };

  u64max_minus_i = function(i) {
    var a, b, x, y;
    x = Math.floor(i / U32MAX);
    y = i % U32MAX;
    a = U32MAX - x - (y > 0 ? 1 : 0);
    b = y === 0 ? 0 : U32MAX - y;
    return [a, b];
  };

  exports.Packer = Packer = (function() {

    function Packer() {
      this._buffer = new Buffer();
    }

    Packer.prototype.output = function(enc) {
      return this._buffer.toString(enc);
    };

    Packer.prototype.p = function(o) {
      switch (typeof o) {
        case 'number':
          return this.p_number(o);
        case 'string':
          return this.p_bytes(o);
        case 'boolean':
          return this.p_boolean(o);
        case 'undefined':
          return this.p_null();
        case 'object':
          if (!(o != null)) {
            return this.p_null();
          } else if (is_array(o)) {
            return this.p_array(o);
          } else {
            return this.p_obj(o);
          }
      }
    };

    Packer.prototype.p_number = function(n) {
      if (!is_int(n)) {
        return this.p_pack_double(n);
      } else if (n >= 0) {
        return this.p_positive_int(n);
      } else {
        return this.p_negative_int(n);
      }
    };

    Packer.prototype.p_pack_double = function(d) {
      var cnv;
      cnv = floats.Converter.make(this._buffer);
      if (cnv != null) {
        this.p_byte(C.double);
        return cnv.pack_float64(d);
      } else {
        return this.p_number(Math.floor(d));
      }
    };

    Packer.prototype.p_byte = function(b) {
      return this._buffer.push_byte(twos_compl(b, 8));
    };

    Packer.prototype.p_short = function(s) {
      return this._buffer.push_short(twos_compl(s, 16));
    };

    Packer.prototype.p_int = function(i) {
      return this._buffer.push_int(twos_compl(i, 32));
    };

    Packer.prototype.p_neg_int64 = function(i) {
      var a, abs_i, b, _ref1;
      abs_i = 0 - i;
      _ref1 = u64max_minus_i(abs_i), a = _ref1[0], b = _ref1[1];
      this.p_int(a);
      return this.p_int(b);
    };

    Packer.prototype.p_boolean = function(b) {
      return this.p_byte(b ? C["true"] : C["false"]);
    };

    Packer.prototype.p_null = function() {
      return this.p_byte(C["null"]);
    };

    Packer.prototype.p_array = function(a) {
      var e, _i, _len, _results;
      this.p_len(a.length, C.fix_array_min, C.fix_array_max, C.array16, C.array32);
      _results = [];
      for (_i = 0, _len = a.length; _i < _len; _i++) {
        e = a[_i];
        _results.push(this.p(e));
      }
      return _results;
    };

    Packer.prototype.p_obj = function(o) {
      var k, n, v, _results;
      n = (Object.keys(o)).length;
      this.p_len(n, C.fix_map_min, C.fix_map_max, C.map16, C.map32);
      _results = [];
      for (k in o) {
        v = o[k];
        this.p(k);
        _results.push(this.p(v));
      }
      return _results;
    };

    Packer.prototype.p_positive_int = function(i) {
      if (i <= 0x7f) {
        return this.p_byte(i);
      } else if (i <= 0xff) {
        this.p_byte(C.uint8);
        return this.p_byte(i);
      } else if (i <= 0xffff) {
        this.p_byte(C.uint16);
        return this.p_short(i);
      } else if (i < U32MAX) {
        this.p_byte(C.uint32);
        return this.p_int(i);
      } else {
        this.p_byte(C.uint64);
        this.p_int(Math.floor(i / U32MAX));
        return this.p_int(i & (U32MAX - 1));
      }
    };

    Packer.prototype.p_negative_int = function(i) {
      if (i >= -32) {
        return this.p_byte(i);
      } else if (i >= -128) {
        this.p_byte(C.int8);
        return this.p_byte(i);
      } else if (i >= -32768) {
        this.p_byte(C.int16);
        return this.p_short(i);
      } else if (i >= -2147483648) {
        this.p_byte(C.int32);
        return this.p_int(i);
      } else {
        this.p_byte(C.int64);
        return this.p_neg_int64(i);
      }
    };

    Packer.prototype.p_bytes = function(b) {
      this.p_len(b.length, C.fix_raw_min, C.raw16, C.raw32);
      return this._buffer.push_bytes(b);
    };

    Packer.prototype.p_len = function(l, smin, smax, m, b) {
      if (l <= (smax - smin)) {
        return this.p_byte(l | smin);
      } else if (l <= 0xffff) {
        this.p_byte(m);
        return this.p_short(l);
      } else {
        this.p_byte(b);
        return this.p_int(l);
      }
    };

    return Packer;

  })();

  exports.pack = function(x, enc) {
    var packer;
    packer = new Packer();
    packer.p(x);
    return packer.output(enc);
  };

}).call(this);
